### ISSUE TITLE
Is the project dead?

### ISSUE THREAD

**Issue by aonemd** [lispunion/code-formatter#2]
Hello, I recently came across scheme-format and I'm using it personally. I see many places for improvements however, I don't see any recent activity on the repository. So my question is if the project is dead. Should I send my pull requests here? Should I make a fork? 

Thanks.

**Comment by lassik** [comment]
[Not dead, just resting](https://en.wikipedia.org/wiki/Dead_Parrot_sketch) :)

I've been meaning to get to it, but there are not that many Lisp hackers and I'm stretched too thin with many projects. Pull requests to this repo are very welcome. I can give you direct write access if you want to.

There are some good papers on pretty-printing that would make a solid foundation for a formatter that does line-wrapping. Wadler's [_A prettier printer_](https://homepages.inf.ed.ac.uk/wadler/papers/prettier/prettier.pdf) may be all that's needed.

**Comment by aonemd** [comment]
Thanks for replying. It's great to hear that the project is not yet dead. I'd be glad to contribute to it here.
