### ISSUE TITLE
Possibility to merge masukomi/scheme-format?

### ISSUE THREAD

**Issue by aonemd** [lispunion/code-formatter#3]
I think that https://github.com/masukomi/scheme-format could be a good starting point for resuming the work on the project. What do you think about merging this fork and starting from there?

**Comment by lassik** [comment]
The readme says:

> A straight port of code-formatter (previously known as "scheme-format") to Chicken 5.x with a minor amount of cleanup.

So yes, we should probably use it.

**Comment by lassik** [comment]
@masukomi what do you think?

**Comment by lassik** [comment]
Code has now been merged.
